
// get all
GET http://localhost:8080/plants

###

// create one
POST http://localhost:8080/plants
Content-Type: application/json

{
  "name": "TEST",
  "id": "9",
  "latinName": "lsnvls",
  "imgUrl": "lsnvls",
  "description": "lsnvls"
}

###

// get one
GET http://localhost:8080/plants/5e28bc72d637549723e157a9

###

// delete one
DELETE http://localhost:8080/plants/5e28bc72d637549723e157a9

###

// update one
PATCH http://localhost:8080/plants/5e28bc72d637549723e157a9
Content-Type: application/json 

{
  "name": "testAH"
}